FROM maven:3-openjdk-8
LABEL purpose="activity" author="jyothi"
ADD https://referenceapplicationskhaja.s3.us-west-2.amazonaws.com/gameoflife.war /usr/local/webapps/gameoflife.war
EXPOSE 8080
# CMD ["catalina.sh" "run"]